name: yes_no_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-35.0.dev <4.0.0'

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
